import { Factory } from 'fishery'

const currentTime = new Date().toISOString()

export const gameFactory = Factory.define<Game>(({ sequence }) => ({
  ageRatings: [],
  artworks: [],
  bannerImage: {
    mobile: {
      url: `https://test.com/storage/uploads/games/${sequence}/mobile_blah.webp`,
    },
    url: `https://test.com/storage/uploads/games/${sequence}/blah.webp`,
  },
  cover: {
    animated: false,
    createdAt: currentTime,
    height: 24,
    id: sequence,
    igdbId: sequence * Math.random(),
    imageId: `cover-image-${sequence}`,
    updatedAt: currentTime,
    url: '',
    width: 56,
  },
  createdAt: currentTime,
  developers: [],
  featuredVideoId: '',
  firstReleaseDate: '',
  franchises: [],
  gameEngines: [],
  gameModes: [],
  genres: [],
  id: sequence,
  igdbId: sequence * Math.random(),
  name: 'Super Metroid',
  platforms: [],
  playerPerspectives: [],
  porters: [],
  published: true,
  publishedAt: '2025-03-12T15:57',
  publishers: [],
  rating: 5,
  releaseDates: [],
  review: '<p>So good</p>',
  screenshots: [],
  slug: 'super-metroid',
  storyline: '',
  summary: '',
  supporters: [],
  themes: [],
  updatedAt: currentTime,
  videos: [],
  websites: [],
}))
