type IconType =
  | 'chevron-double-left'
  | 'chevron-double-right'
  | 'chevron-left'
  | 'close'
  | 'edit'
  | 'filter-alt'
  | 'image'
  | 'magnify'
  | 'message-draw'
  | 'outline-filter-alt'
  | 'plus-thick'
  | 'round-sort'
  | 'table'
  | 'trash'
  | 'user'
  | 'videogame'
