/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/age_ratings/:id payload
 */
interface AgeRatingsShowJson {
  ageRating: AgeRating
}
/**
 * An AgeRating.
 */
interface AgeRating {
  createdAt: string
  id: number
  igdbId: number
  /**
   * The url for the image of a age rating.
   */
  ratingCoverUrl: string
  /**
   * A free text motivating a rating.
   */
  synopsis: string
  updatedAt: string
}
