/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/companies/:id payload
 */
interface CompaniesShowJson {
  company: Company
}
/**
 * A Company.
 */
interface Company {
  /**
   * ISO 3166-1 country code.
   */
  countryCode: number | null
  createdAt: string
  description: string
  id: number
  igdbId: number
  name: string
  slug: string
  /**
   * The date the company was founded.
   */
  startDate: string | null
  updatedAt: string
}
