/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/covers/:id payload
 */
interface CoversShowJson {
  cover: Cover
}
/**
 * A Cover.
 */
interface Cover {
  animated: boolean
  createdAt: string
  height: number
  id: number
  igdbId: number
  imageId: string
  updatedAt: string
  url: string
  width: number
}
