/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Franchise.
 */
interface Franchise {
  createdAt: string
  id: number
  igdbId: number
  /**
   * Whether or not the franchise is the main franchise of the game.
   */
  main: boolean
  name: string
  slug: string
  updatedAt: string
}
