/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/game_engines/:id payload
 */
interface GameEnginesShowJson {
  gameEngine: GameEngine
}
/**
 * A GameEngine.
 */
interface GameEngine {
  createdAt: string
  description: string
  id: number
  igdbId: number
  name: string
  slug: string
  updatedAt: string
}
