/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/game_filters payload
 */
interface GameFiltersIndexJson {
  filters: {
    companies: Company[]
    genres: GenreWithoutResources[]
    platforms: PlatformWithoutResources[]
  }
}
/**
 * A Company.
 */
interface Company {
  /**
   * ISO 3166-1 country code.
   */
  countryCode: number | null
  createdAt: string
  description: string
  id: number
  igdbId: number
  name: string
  slug: string
  /**
   * The date the company was founded.
   */
  startDate: string | null
  updatedAt: string
}
/**
 * A version of a Genre that doesn't include relational resources.
 */
interface GenreWithoutResources {
  createdAt: string
  id: number
  igdbId: number
  name: string
  slug: string
  updatedAt: string
}
/**
 * A version of a Platform that doesn't include relational resources.
 */
interface PlatformWithoutResources {
  /**
   * An abbreviated name for the platform.
   */
  abbreviation: string
  /**
   * An alternative name for the platform.
   */
  alternativeName: string
  createdAt: string
  generation: number | null
  id: number
  igdbId: number
  name: string
  slug: string
  /**
   * The summary of the first Version of this platform.
   */
  summary: string
  updatedAt: string
}
