/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/platforms payload
 */
interface PlatformsIndexJson {
  platforms: PlatformWithoutResources[]
}
/**
 * A version of a Platform that doesn't include relational resources.
 */
interface PlatformWithoutResources {
  /**
   * An abbreviated name for the platform.
   */
  abbreviation: string
  /**
   * An alternative name for the platform.
   */
  alternativeName: string
  createdAt: string
  generation: number | null
  id: number
  igdbId: number
  name: string
  slug: string
  /**
   * The summary of the first Version of this platform.
   */
  summary: string
  updatedAt: string
}
