/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/screenshots/:id payload
 */
interface ScreenshotsShowJson {
  screenshot: Screenshot
}
/**
 * A Screenshot.
 */
interface Screenshot {
  animated: boolean
  createdAt: string
  height: number
  id: number
  igdbId: number
  updatedAt: string
  url: string
  width: number
}
