/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GET /api/users payload
 */
interface UsersIndexJson {
  users: User[]
}
/**
 * A User.
 */
interface User {
  /**
   * A flag for whether or not the user is an admin.
   */
  admin: boolean
  /**
   * The email used to register the user.
   */
  email: string
  firstName: string
  id: number
  lastName: string
  username: string
}
